from typing import Protocol


class Conn(Protocol):
    def recv(self, size: int) -> bytes: ...
    def send(self, data: bytes) -> int: ...
    def settimeout(self, t: float | None) -> None: ...
    def close(self) -> None: ...
